// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-cQhGKDW-6tgdD52Fy5vMpc7RXevDjfY',
    appId: '1:306525797163:web:995d105ff1d2e65031636e',
    messagingSenderId: '306525797163',
    projectId: 'chatapp-6af69',
    authDomain: 'chatapp-6af69.firebaseapp.com',
    storageBucket: 'chatapp-6af69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6soMd4Tlgp9yptRUpizkV0_SXRU38ahg',
    appId: '1:306525797163:android:221a6ab195d579aa31636e',
    messagingSenderId: '306525797163',
    projectId: 'chatapp-6af69',
    storageBucket: 'chatapp-6af69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84yrGNNQ7PBFWsO15GsdMWPZO6MvhCeA',
    appId: '1:306525797163:ios:60c818bfb571c2b731636e',
    messagingSenderId: '306525797163',
    projectId: 'chatapp-6af69',
    storageBucket: 'chatapp-6af69.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84yrGNNQ7PBFWsO15GsdMWPZO6MvhCeA',
    appId: '1:306525797163:ios:60c818bfb571c2b731636e',
    messagingSenderId: '306525797163',
    projectId: 'chatapp-6af69',
    storageBucket: 'chatapp-6af69.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-cQhGKDW-6tgdD52Fy5vMpc7RXevDjfY',
    appId: '1:306525797163:web:96eb46b8f841ab8231636e',
    messagingSenderId: '306525797163',
    projectId: 'chatapp-6af69',
    authDomain: 'chatapp-6af69.firebaseapp.com',
    storageBucket: 'chatapp-6af69.appspot.com',
  );
}
